---
extends: airbnb
env:
  jest: true
rules:
  import/no-extraneous-dependencies:
    - error
    - optionalDependencies: false
      devDependencies:
      - '**/__mocks__/**/*.{js,jsx}'
      - '**/*.{test,story}.{js,jsx}'
      - '**/jest.setup.js'
      - 'next.config.js'
      - 'config/**/*.js'
  max-len: [2, 79]
  react/sort-prop-types: 2
  react/no-unescaped-entities: 0
  react/jsx-filename-extension: 0
  react/prop-types: [2, {ignore: ['children']}]
  jsx-a11y/label-has-for: ['error', { components: ['label'], allowChildren: true }]
  jsx-a11y/anchor-is-valid: 0
parser: babel-eslint
